name: Rust-Cargo Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: Terracotta Version
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  name: terracotta
  RUST_BACKTRACE: full
  TERRACOTTA_U_S: ${{ secrets.TERRACOTTA_U_S }}

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: windows-latest
            os: windows
            arch: x86_64
            target: x86_64-pc-windows-msvc
          - runs-on: windows-11-arm
            os: windows
            arch: arm64
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.runs-on }}
    name: Build (${{ matrix.target }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly "${{ matrix.target }}"
          rustup component add rust-src --toolchain "nightly-$(rustc --print host-tuple)"
          cargo +nightly build --release --bin terracotta --target "${{ matrix.target }}" \
            -Z build-std=core,std,alloc,proc_macro,panic_abort \
            -Z build-std-features=default,optimize_for_size
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=immediate-abort
      - name: Upload Artifact
        run: |
          source="terracotta-${TERRACOTTA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.exe"
          cp "target/${{ matrix.target }}/release/terracotta.exe" "$source"
          7z a "$source.zip" "$source"
          cat "$source.zip" | gh-actions-artifact-client.js upload -r 90 "$source"
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: linux,   arch: x86_64,      target: x86_64-unknown-linux-musl }
          - { os: linux,   arch: arm64,       target: aarch64-unknown-linux-musl,  runs-on: ubuntu-24.04-arm }
          - { os: linux,   arch: riscv64,     target: riscv64gc-unknown-linux-gnu, glibc-version: 2.27 }
          - { os: linux,   arch: loongarch64, target: loongarch64-unknown-linux-gnu }
          - { os: freebsd, arch: x86_64,      target: x86_64-unknown-freebsd }
          - { os: android, arch: armv7      , target: armv7-linux-androideabi }
          - { os: android, arch: arm64v8a,    target: aarch64-linux-android }
          - { os: android, arch: x86,         target: i686-linux-android }
          - { os: android, arch: x86_64,      target: x86_64-linux-android }
    runs-on: ${{ matrix.runs-on || 'ubuntu-24.04' }}
    name: Build (${{ matrix.target }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Setup Android SDK (Android)
        if: ${{ matrix.os == 'android' }}
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: 'build-tools;34.0.0 ndk;26.0.10792818 tools platform-tools platforms;android-34 '
      - name: Install cargo-ndk and protobuf-compiler (Android)
        if: ${{ matrix.os == 'android' }}
        run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends protobuf-compiler libprotobuf-dev
          cargo install cargo-ndk --force
      - name: Install musl libc (linux x86_64 | linux arm64)
        if: ${{ contains(fromJSON('["x86_64", "arm64"]'), matrix.arch) && matrix.os == 'linux' }}
        run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends build-essential musl-tools musl-dev
      - name: Install Zig (linux riscv64 | linux loongarch64)
        if: ${{ contains(fromJSON('["riscv64", "loongarch64"]'), matrix.arch) && matrix.os == 'linux' }}
        uses: mlugg/setup-zig@v2
      - name: Install cargo-zigbuild (linux riscv64 | linux loongarch64)
        if: ${{ contains(fromJSON('["riscv64", "loongarch64"]'), matrix.arch) && matrix.os == 'linux' }}
        run: cargo install cargo-zigbuild --force
      - name: Build (linux x86_64 | linux arm64)
        if: ${{ contains(fromJSON('["x86_64", "arm64"]'), matrix.arch) && matrix.os == 'linux' }}
        run: |
          rustup target add --toolchain nightly "${{ matrix.target }}"
          rustup component add rust-src --toolchain "nightly-$(rustc --print host-tuple)"
          cargo +nightly build --release --bin terracotta --target "${{ matrix.target }}" \
            -Z build-std=core,std,alloc,proc_macro,panic_abort \
            -Z build-std-features=default,optimize_for_size
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=immediate-abort
      - name: Build (linux riscv64 | linux loongarch64)
        if: ${{ contains(fromJSON('["riscv64", "loongarch64"]'), matrix.arch) && matrix.os == 'linux' }}
        run: |
          rustup target add --toolchain nightly "${{ matrix.target }}"
          cargo +nightly zigbuild --release --bin terracotta --target "${{ matrix.target }}.${{ matrix.glibc-version }}"
      - name: Build (freebsd x86_64)
        if: ${{ contains(fromJSON('["x86_64"]'), matrix.arch) && matrix.os == 'freebsd' }}
        uses: cross-platform-actions/action@v0.30.0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.arch }}
          version: '13.2'
          shell: bash
          run: |
            sudo pkg install -y llvm-devel curl ca_root_nss
            curl --proto 'https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            export CC=clang
            export CXX=clang++
            . $HOME/.cargo/env
            rustup target add --toolchain nightly "${{ matrix.target }}"
            cargo +nightly build --release --bin terracotta --target "${{ matrix.target }}"
      - name: Build (Android)
        if: ${{ matrix.os == 'android' }}
        run: |
          export PATH="$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export NDK_HOME="$ANDROID_NDK_HOME"
          
          rustup target add --toolchain nightly "${{ matrix.target }}"
          rustup component add rust-src --toolchain "nightly-$(rustc --print host-tuple)"
          cargo +nightly ndk build --release --lib --target "${{ matrix.target }}" \
            -Z build-std=core,std,alloc,proc_macro,panic_abort \
            -Z build-std-features=default,optimize_for_size
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=unwind
      - name: Upload Artifact
        run: |
          if [ "${{ matrix.os }}" = "android" ]; then
            source="terracotta-${TERRACOTTA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.so"
            cp "target/${{ matrix.target }}/release/libterracotta.so" "$source"
          else
            source="terracotta-${TERRACOTTA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}"
            cp "target/${{ matrix.target }}/release/terracotta" "$source"
          fi
          
          chmod 755 "$source"
          tar -cf "$source.tar" "$source"
          zip -q - "$source.tar" | gh-actions-artifact-client.js upload -r 90 "$source.tar"
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-15-intel
            os: macos
            arch: x86_64
            target: x86_64-apple-darwin
          - runs-on: macos-latest
            os: macos
            arch: arm64
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runs-on }}
    name: Build (${{ matrix.target }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly "${{ matrix.target }}"
          rustup component add rust-src --toolchain "nightly-$(rustc --print host-tuple)"
          cargo +nightly build --release --bin terracotta --target "${{ matrix.target }}" \
            -Z build-std=core,std,alloc,proc_macro,panic_abort \
            -Z build-std-features=default,optimize_for_size
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=immediate-abort
      - name: Upload Artifact
        run: |
          source="terracotta-${TERRACOTTA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}"
          
          cp "target/${{ matrix.target }}/release/terracotta" "$source"
          chmod 755 "$source"
          tar -cf "$source.tar" "$source"
          zip -q - "$source.tar" | gh-actions-artifact-client.js upload -r 90 "$source.tar"
          
          chmod -R 755 build/macos/scripts
          TEMP_DIR=$(mktemp -d)
          mkdir -p "$TEMP_DIR"
          
          cp -R build/macos/terracotta.app "$TEMP_DIR"
          mkdir -p "$TEMP_DIR/terracotta.app/Contents/MacOS/"
          cp "target/${{ matrix.target }}/release/terracotta" "$TEMP_DIR/terracotta.app/Contents/MacOS/terracotta"
          
          chmod -R 755 "$TEMP_DIR/"
          PKG_OUTPUT="$source.pkg"
          
          pkgbuild \
            --root "$TEMP_DIR" \
            --identifier "net.burningtnt.terracotta" \
            --version "1.0" \
            --install-location "/Applications" \
            --scripts build/macos/scripts \
            --component-plist build/macos/terracotta.plist \
            "$PKG_OUTPUT"
          zip -q - $PKG_OUTPUT | gh-actions-artifact-client.js upload -r 90 "$source.pkg"
  assemble-packages:
    runs-on: ubuntu-latest
    name: Assemble Artifact
    needs:
      - build-windows
      - build-unix
      - build-macos
    steps:
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Assemble Artifacts
        run: |
          artifacts_direct=(
            "terracotta-${TERRACOTTA_VERSION}-windows-x86_64.exe"
            "terracotta-${TERRACOTTA_VERSION}-windows-arm64.exe"
            "terracotta-${TERRACOTTA_VERSION}-macos-x86_64.pkg"
            "terracotta-${TERRACOTTA_VERSION}-macos-arm64.pkg"
          )
          artifacts_tar=(
            "terracotta-${TERRACOTTA_VERSION}-linux-x86_64"
            "terracotta-${TERRACOTTA_VERSION}-linux-arm64"
            "terracotta-${TERRACOTTA_VERSION}-linux-riscv64"
            "terracotta-${TERRACOTTA_VERSION}-linux-loongarch64"
            "terracotta-${TERRACOTTA_VERSION}-freebsd-x86_64"
            "terracotta-${TERRACOTTA_VERSION}-macos-x86_64"
            "terracotta-${TERRACOTTA_VERSION}-macos-arm64"
            "terracotta-${TERRACOTTA_VERSION}-android-armv7.so"
            "terracotta-${TERRACOTTA_VERSION}-android-arm64v8a.so"
            "terracotta-${TERRACOTTA_VERSION}-android-x86.so"
            "terracotta-${TERRACOTTA_VERSION}-android-x86_64.so"
          )
          
          file=$(mktemp -t XXXXXX.zip)
          for artifact in "${artifacts_direct[@]}"; do
            gh-actions-artifact-client.js download "$artifact" > "$file"
            unzip -p "$file" > "$artifact"
          done
          for artifact in "${artifacts_tar[@]}"; do
            gh-actions-artifact-client.js download "$artifact.tar" > "$file"
            unzip -p "$file" | tar -xOf - > "$artifact"
          done
          rm "$file"
          
          chmod 755 terracotta-${TERRACOTTA_VERSION}-*
          7z -m0=LZMA2 -mx=9 -ms=on a terracotta.7z terracotta-${TERRACOTTA_VERSION}-*
          zip -r - terracotta.7z | gh-actions-artifact-client.js upload -r 90 "terracotta-${TERRACOTTA_VERSION}-all.7z"
          
          if [ ! -z "${{ github.event.inputs.version }}" ]; then
            mkdir -p bundle
          
            curl -L -o VCRUNTIME140.DLL "https://github.com/burningtnt/Terracotta/raw/refs/heads/binaries/windows_x86_64/vcruntime140.dll"
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-windows-x86_64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-windows-x86_64.exe VCRUNTIME140.DLL
            curl -L -o VCRUNTIME140.DLL "https://github.com/burningtnt/Terracotta/raw/refs/heads/binaries/windows_arm64/vcruntime140.dll"
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-windows-arm64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-windows-arm64.exe VCRUNTIME140.DLL
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-linux-x86_64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-linux-x86_64
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-linux-arm64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-linux-arm64
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-linux-riscv64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-linux-riscv64
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-linux-loongarch64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-linux-loongarch64
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-freebsd-x86_64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-freebsd-x86_64
          
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-macos-x86_64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-macos-x86_64 terracotta-${TERRACOTTA_VERSION}-macos-x86_64.pkg
            tar -czvf bundle/terracotta-${TERRACOTTA_VERSION}-macos-arm64-pkg.tar.gz terracotta-${TERRACOTTA_VERSION}-macos-arm64 terracotta-${TERRACOTTA_VERSION}-macos-arm64.pkg
          
            cp terracotta-${TERRACOTTA_VERSION}-android-armv7.so bundle/terracotta-${TERRACOTTA_VERSION}-android-armv7.so
            cp terracotta-${TERRACOTTA_VERSION}-android-arm64v8a.so bundle/terracotta-${TERRACOTTA_VERSION}-android-arm64v8a.so
            cp terracotta-${TERRACOTTA_VERSION}-android-x86.so bundle/terracotta-${TERRACOTTA_VERSION}-android-x86.so
            cp terracotta-${TERRACOTTA_VERSION}-android-x86_64.so bundle/terracotta-${TERRACOTTA_VERSION}-android-x86_64.so
          
            gh release create v"${{ github.event.inputs.version }}" -R "${{ github.repository }}" --draft --generate-notes bundle/terracotta-${TERRACOTTA_VERSION}-*
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
